# Generated by Django 6.0 on 2026-01-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_fishing_choices_post_hunting_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fishing_zone_choices',
            field=models.CharField(choices=[('freshwater', 'Freshwater'), ('coastal', 'Coastal Saltwater'), ('offshore', 'Offshore / Deep Sea'), ('shark', 'Shark')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='fishing_choices',
            field=models.CharField(choices=[('none', 'None'), ('bass_largemouth', 'Largemouth Bass'), ('bass_smallmouth', 'Smallmouth Bass'), ('bass_spotted', 'Spotted Bass'), ('trout_rainbow', 'Rainbow Trout'), ('trout_brown', 'Brown Trout'), ('trout_brook', 'Brook Trout'), ('trout_cutthroat', 'Cutthroat Trout'), ('trout_lake', 'Lake Trout'), ('walleye', 'Walleye'), ('pike_northern', 'Northern Pike'), ('muskellunge', 'Muskellunge'), ('catfish_channel', 'Channel Catfish'), ('catfish_blue', 'Blue Catfish'), ('catfish_flathead', 'Flathead Catfish'), ('crappie_black', 'Black Crappie'), ('crappie_white', 'White Crappie'), ('perch_yellow', 'Yellow Perch'), ('sunfish_bluegill', 'Bluegill'), ('carp_common', 'Common Carp'), ('trout_speckled', 'Spotted Seatrout (Speckled Trout)'), ('trout_sand', 'Sand Seatrout'), ('trout_silver', 'Silver Seatrout'), ('trout_weakfish', 'Weakfish (Gray Seatrout)'), ('black_drum', 'Black Drum'), ('sheepshead', 'Sheepshead'), ('redfish', 'Red Drum (Redfish)'), ('snook', 'Snook'), ('striped_bass', 'Striped Bass'), ('tarpon', 'Tarpon'), ('flounder', 'Flounder'), ('snapper_red', 'Red Snapper'), ('grouper', 'Grouper'), ('halibut_pacific', 'Pacific Halibut'), ('amberjack', 'Greater Amberjack'), ('tuna_bluefin', 'Bluefin Tuna'), ('tuna_yellowfin', 'Yellowfin Tuna'), ('tuna_bigeye', 'Bigeye Tuna'), ('swordfish', 'Swordfish'), ('marlin_blue', 'Blue Marlin'), ('marlin_white', 'White Marlin'), ('sailfish', 'Sailfish'), ('wahoo', 'Wahoo'), ('mahi_mahi', 'Mahi-Mahi (Dolphinfish)'), ('shark_blacktip', 'Blacktip Shark'), ('shark_spinner', 'Spinner Shark'), ('shark_bull', 'Bull Shark'), ('shark_lemon', 'Lemon Shark'), ('shark_tiger', 'Tiger Shark'), ('shark_sandbar', 'Sandbar Shark'), ('shark_smooth_dogfish', 'Smooth Dogfish Shark'), ('shark_atlantic_sharpnose', 'Atlantic Sharpnose Shark'), ('shark_bonnethead', 'Bonnethead Shark')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='hunting_choices',
            field=models.CharField(choices=[('none', 'None'), ('deer_whitetail', 'White-tailed Deer'), ('deer_mule', 'Mule/Black-tailed Deer'), ('elk', 'Elk'), ('moose', 'Moose'), ('bear_black', 'Black Bear'), ('bighorn_sheep', 'Bighorn Sheep'), ('mountain_lion', 'Mountain Lion'), ('pronghorn', 'Pronghorn'), ('rabbit', 'Rabbit/Hare'), ('squirrel', 'Squirrel'), ('raccoon', 'Raccoon'), ('coyote', 'Coyote'), ('fox', 'Fox'), ('turkey', 'Wild Turkey'), ('grouse', 'Grouse'), ('quail', 'Quail'), ('pheasant', 'Pheasant'), ('dove', 'Dove'), ('duck', 'Duck'), ('goose', 'Goose'), ('rail', 'Rail/Snipe')], default='draft', max_length=50),
        ),
    ]
