# Generated by Django 6.0 on 2026-01-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_fishing_zone_choices_alter_post_fishing_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='No description yet', max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='fishing_zone_choices',
            field=models.CharField(choices=[('none', 'None'), ('freshwater', 'Freshwater'), ('coastal', 'Coastal Saltwater'), ('offshore', 'Offshore / Deep Sea'), ('shark', 'Shark')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
