# Generated by Django 6.0 on 2026-01-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_fishing_hunting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvested',
            name='species',
        ),
        migrations.RemoveField(
            model_name='harvested',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.AddField(
            model_name='fishing',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hunting',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fishing',
            name='fishing_zone_choices',
            field=models.CharField(choices=[('none', 'None'), ('freshwater', 'Freshwater'), ('coastal', 'Coastal Saltwater'), ('offshore', 'Offshore / Deep Sea')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='fishing_zone_choices',
            field=models.CharField(choices=[('none', 'None'), ('freshwater', 'Freshwater'), ('coastal', 'Coastal Saltwater'), ('offshore', 'Offshore / Deep Sea')], default='draft', max_length=50),
        ),
        migrations.DeleteModel(
            name='Species',
        ),
        migrations.DeleteModel(
            name='Harvested',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
