# Generated by Django 6.0 on 2026-01-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_fishing_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hunting_choices',
            field=models.CharField(choices=[('none', 'None'), ('deer_whitetail', 'White-tailed Deer'), ('deer_mule', 'Mule/Black-tailed Deer'), ('elk', 'Elk'), ('moose', 'Moose'), ('hog', 'Hog'), ('bear_black', 'Black Bear'), ('bighorn_sheep', 'Bighorn Sheep'), ('mountain_lion', 'Mountain Lion'), ('pronghorn', 'Pronghorn'), ('rabbit', 'Rabbit/Hare'), ('squirrel', 'Squirrel'), ('raccoon', 'Raccoon'), ('coyote', 'Coyote'), ('fox', 'Fox'), ('turkey', 'Wild Turkey'), ('grouse', 'Grouse'), ('quail', 'Quail'), ('pheasant', 'Pheasant'), ('dove', 'Dove'), ('duck', 'Duck'), ('goose', 'Goose'), ('rail', 'Rail/Snipe')], default='none', max_length=50),
        ),
    ]
