# Generated by Django 6.0 on 2026-01-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_post_hunting_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishing',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hunting',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
