# Generated by Django 6.0 on 2026-01-17 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_fishing_description_alter_hunting_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishing',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hunting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
