# Generated by Django 6.0 on 2026-01-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_post_fishing_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunting',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
