# Generated by Django 6.0 on 2026-01-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_hunting_description_remove_post_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunting',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
